'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Project, projectSchema } from '@/lib/types';
import { createProject, createProjectWithAI } from '@/app/actions';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { CalendarIcon, Loader2, Sparkles, Plus, Copy, FileText, ArrowRight, ArrowLeft } from 'lucide-react';

type WizardMode = 'choice' | 'ai' | 'manual' | 'duplicate';

export function ProjectCreationWizard() {
  const [open, setOpen] = useState(false);
  const [wizardMode, setWizardMode] = useState<WizardMode>('choice');
  const [step, setStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const form = useForm<Project>({
    resolver: zodResolver(projectSchema),
    defaultValues: {
      projectName: '',
      contractType: 'Fixed Price',
      securityClassification: 'Unclassified',
      projectStartDate: new Date(),
      projectEndDate: new Date(new Date().setMonth(new Date().getMonth() + 6)),
      wbsPopulationMethod: 'Load from JL2 Templates',
      defaultProfitMargin: 10,
      managementReserve: 5,
      projectSpecificContingency: 5,
      annualCostEscalationRate: 2.5,
      defaultGstTreatment: 'Exclusive',
      projectCurrency: 'AUD',
      requiredClearance: 'N/A',
    },
  });

  const resetWizard = () => {
    setWizardMode('choice');
    setStep(1);
    form.reset();
  };
  
  const handleOpenChange = (isOpen: boolean) => {
    if (isOpen) {
      resetWizard();
    }
    setOpen(isOpen);
  }

  const handleAiGenerate = async (data: { description: string }) => {
    setIsSubmitting(true);
    const result = await createProjectWithAI(data.description);
    if (result.success && result.data) {
      form.reset(result.data);
      setWizardMode('manual');
      setStep(5); // Go to review step
      toast({
        title: 'Project Generated!',
        description: 'Review the details generated by AI.',
      });
    } else {
      toast({
        variant: 'destructive',
        title: 'AI Generation Failed',
        description: result.error,
      });
    }
    setIsSubmitting(false);
  };
  
  const onSubmit = async (data: Project) => {
    setIsSubmitting(true);
    const result = await createProject(data);
    if(result.success) {
      toast({
        title: "Project Created!",
        description: `Project "${data.projectName}" has been created successfully.`,
      });
      setOpen(false);
    } else {
       toast({
        variant: 'destructive',
        title: 'Creation Failed',
        description: result.error,
      });
    }
    setIsSubmitting(false);
  }
  
  const steps = [
    { id: 1, name: 'Contract Details' },
    { id: 2, name: 'Timeline & WBS' },
    { id: 3, name: 'Financials' },
    { id: 4, name: 'Compliance' },
    { id: 5, name: 'Review & Create' },
  ];

  const nextStep = () => setStep((s) => Math.min(s + 1, steps.length));
  const prevStep = () => setStep((s) => Math.max(s - 1, 1));

  const renderContent = () => {
    if (wizardMode === 'choice') {
      return (
        <>
          <DialogHeader>
            <DialogTitle>Create New Project</DialogTitle>
            <DialogDescription>How would you like to create your project?</DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-1 gap-4 py-4 md:grid-cols-3">
            <button onClick={() => setWizardMode('ai')} className="flex flex-col items-center justify-center gap-2 rounded-lg border p-6 text-center transition-all hover:bg-accent hover:text-accent-foreground">
              <Sparkles className="h-8 w-8 text-accent" />
              <span className="font-semibold">Generate with AI</span>
            </button>
            <button onClick={() => setWizardMode('manual')} className="flex flex-col items-center justify-center gap-2 rounded-lg border p-6 text-center transition-all hover:bg-accent hover:text-accent-foreground">
              <FileText className="h-8 w-8 text-primary" />
              <span className="font-semibold">New Blank Project</span>
            </button>
            <button onClick={() => {toast({description: "Feature coming soon!"});}} className="flex flex-col items-center justify-center gap-2 rounded-lg border p-6 text-center transition-all hover:bg-accent hover:text-accent-foreground disabled:opacity-50 disabled:hover:bg-transparent" disabled>
              <Copy className="h-8 w-8 text-muted-foreground" />
              <span className="font-semibold text-muted-foreground">Duplicate Project</span>
            </button>
          </div>
        </>
      );
    }

    if (wizardMode === 'ai') {
      return (
        <>
          <DialogHeader>
            <DialogTitle>Generate with AI</DialogTitle>
            <DialogDescription>Describe your project, and AI will create a draft for you.</DialogDescription>
          </DialogHeader>
          <form onSubmit={(e) => { e.preventDefault(); handleAiGenerate({ description: (e.target as any).description.value }); }}>
            <div className="py-4">
              <Textarea id="description" name="description" placeholder="e.g., 'Build a 6-month Systems Engineering project for a Defence client, NV1 clearance required, on a Cost Plus basis'" className="min-h-[120px]" />
            </div>
            <DialogFooter>
              <Button type="button" variant="ghost" onClick={() => setWizardMode('choice')}>Back</Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                Generate
              </Button>
            </DialogFooter>
          </form>
        </>
      );
    }

    if (wizardMode === 'manual') {
      return (
         <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="flex h-full flex-col">
              <DialogHeader>
                <DialogTitle>Defence-Grade Project Creation Wizard</DialogTitle>
                <DialogDescription>{steps.find(s => s.id === step)?.name}</DialogDescription>
              </DialogHeader>
              <div className="my-4">
                <div className="flex justify-between">
                  {steps.map((s, i) => (
                    <div key={s.id} className="flex flex-col items-center">
                      <div
                        className={cn(
                          'flex h-8 w-8 items-center justify-center rounded-full border-2',
                          step > s.id ? 'border-primary bg-primary text-primary-foreground' : step === s.id ? 'border-primary' : ''
                        )}
                      >
                        {s.id}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="flex-grow space-y-4 py-4 overflow-y-auto px-1">
                {step === 1 && ( // Step 1: Core Contract Details
                  <div className="space-y-4">
                     <FormField control={form.control} name="projectName" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Project Name</FormLabel>
                        <FormControl><Input placeholder="e.g., RAAF Deployable Mission Planning" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <div className="grid grid-cols-2 gap-4">
                        <FormField control={form.control} name="tenderId" render={({ field }) => (
                            <FormItem>
                            <FormLabel>Tender / RFQ ID</FormLabel>
                            <FormControl><Input placeholder="e.g., CASG-RFQ-2025-123" {...field} /></FormControl>
                            <FormMessage />
                            </FormItem>
                        )} />
                        <FormField control={form.control} name="client" render={({ field }) => (
                            <FormItem>
                            <FormLabel>Client</FormLabel>
                            <FormControl><Input placeholder="e.g., Department of Defence, CASG" {...field} /></FormControl>
                            <FormMessage />
                            </FormItem>
                        )} />
                    </div>
                     <div className="grid grid-cols-2 gap-4">
                        <FormField control={form.control} name="contractType" render={({ field }) => (
                        <FormItem><FormLabel>Contract Type</FormLabel><Select onValueChange={field.onChange} defaultValue={field.value}><FormControl><SelectTrigger><SelectValue placeholder="Select contract type" /></SelectTrigger></FormControl><SelectContent><SelectItem value="Fixed Price">Fixed Price</SelectItem><SelectItem value="Cost Plus">Cost Plus</SelectItem><SelectItem value="Time & Materials (T&M)">Time & Materials (T&M)</SelectItem></SelectContent></Select><FormMessage /></FormItem>
                        )} />
                        <FormField control={form.control} name="securityClassification" render={({ field }) => (
                        <FormItem><FormLabel>Security Classification</FormLabel><Select onValueChange={field.onChange} defaultValue={field.value}><FormControl><SelectTrigger><SelectValue placeholder="Select classification" /></SelectTrigger></FormControl><SelectContent><SelectItem value="Unclassified">Unclassified</SelectItem><SelectItem value="Protected">Protected</SelectItem><SelectItem value="Secret">Secret</SelectItem></SelectContent></Select><FormMessage /></FormItem>
                        )} />
                     </div>
                  </div>
                )}
                {step === 2 && ( // Step 2: Timeline & WBS
                    <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <FormField control={form.control} name="projectStartDate" render={({ field }) => (
                                <FormItem className="flex flex-col"><FormLabel>Project Start Date</FormLabel><Popover><PopoverTrigger asChild><FormControl><Button variant={"outline"} className={cn("pl-3 text-left font-normal", !field.value && "text-muted-foreground")}><CalendarIcon className="mr-2 h-4 w-4" />{field.value ? format(field.value, 'PPP') : <span>Pick a date</span>}</Button></FormControl></PopoverTrigger><PopoverContent className="w-auto p-0" align="start"><Calendar mode="single" selected={field.value} onSelect={field.onChange} /></PopoverContent></Popover><FormMessage /></FormItem>
                            )}/>
                            <FormField control={form.control} name="projectEndDate" render={({ field }) => (
                                <FormItem className="flex flex-col"><FormLabel>Project End Date</FormLabel><Popover><PopoverTrigger asChild><FormControl><Button variant={"outline"} className={cn("pl-3 text-left font-normal", !field.value && "text-muted-foreground")}><CalendarIcon className="mr-2 h-4 w-4" />{field.value ? format(field.value, 'PPP') : <span>Pick a date</span>}</Button></FormControl></PopoverTrigger><PopoverContent className="w-auto p-0" align="start"><Calendar mode="single" selected={field.value} onSelect={field.onChange} /></PopoverContent></Popover><FormMessage /></FormItem>
                            )}/>
                        </div>
                        <FormField control={form.control} name="wbsPopulationMethod" render={({ field }) => (
                            <FormItem className="space-y-3"><FormLabel>WBS Population Method</FormLabel><FormControl><RadioGroup onValueChange={field.onChange} defaultValue={field.value} className="flex flex-col space-y-1"><FormItem className="flex items-center space-x-3 space-y-0"><FormControl><RadioGroupItem value="Load from JL2 Templates" /></FormControl><FormLabel className="font-normal">Load from JL2 Templates</FormLabel></FormItem><FormItem className="flex items-center space-x-3 space-y-0"><FormControl><RadioGroupItem value="Build Custom WBS" /></FormControl><FormLabel className="font-normal">Build Custom WBS</FormLabel></FormItem><FormItem className="flex items-center space-x-3 space-y-0"><FormControl><RadioGroupItem value="Import from MS Project (CSV)" /></FormControl><FormLabel className="font-normal">Import from MS Project (CSV)</FormLabel></FormItem></RadioGroup></FormControl><FormMessage /></FormItem>
                        )}/>
                    </div>
                )}
                {step === 3 && ( // Step 3: Financial & Risk Assumptions
                  <div className="space-y-4">
                     <div className="grid grid-cols-2 gap-4">
                        <FormField control={form.control} name="defaultProfitMargin" render={({ field }) => (<FormItem><FormLabel>Default Profit Margin (%)</FormLabel><FormControl><Input type="number" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="managementReserve" render={({ field }) => (<FormItem><FormLabel>Management Reserve (%)</FormLabel><FormControl><Input type="number" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} /></FormControl><FormMessage /></FormItem>)} />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <FormField control={form.control} name="projectSpecificContingency" render={({ field }) => (<FormItem><FormLabel>Project-Specific Contingency (%)</FormLabel><FormControl><Input type="number" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="annualCostEscalationRate" render={({ field }) => (<FormItem><FormLabel>Annual Cost Escalation Rate (%)</FormLabel><FormControl><Input type="number" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} /></FormControl><FormMessage /></FormItem>)} />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <FormField control={form.control} name="defaultGstTreatment" render={({ field }) => (
                            <FormItem><FormLabel>Default GST Treatment</FormLabel><Select onValueChange={field.onChange} defaultValue={field.value}><FormControl><SelectTrigger><SelectValue/></SelectTrigger></FormControl><SelectContent><SelectItem value="Exclusive">Exclusive</SelectItem><SelectItem value="Inclusive">Inclusive</SelectItem></SelectContent></Select><FormMessage /></FormItem>
                        )}/>
                        <FormField control={form.control} name="projectCurrency" render={({ field }) => (<FormItem><FormLabel>Project Currency</FormLabel><FormControl><Input placeholder="e.g., AUD" {...field} /></FormControl><FormMessage /></FormItem>)} />
                    </div>
                  </div>
                )}
                {step === 4 && ( // Step 4: Compliance & Team
                    <FormField control={form.control} name="requiredClearance" render={({ field }) => (
                        <FormItem><FormLabel>Required Security Clearance</FormLabel><Select onValueChange={field.onChange} defaultValue={field.value}><FormControl><SelectTrigger><SelectValue/></SelectTrigger></FormControl><SelectContent><SelectItem value="N/A">N/A</SelectItem><SelectItem value="Baseline">Baseline</SelectItem><SelectItem value="NV1">NV1</SelectItem><SelectItem value="NV2">NV2</SelectItem></SelectContent></Select><FormMessage /></FormItem>
                    )}/>
                )}
                {step === 5 && ( // Step 5: Review
                    <div className="space-y-4 text-sm">
                        {Object.entries(form.getValues()).map(([key, value]) => (
                            <div key={key} className="flex justify-between border-b pb-2">
                                <span className="font-medium text-muted-foreground capitalize">{key.replace(/([A-Z])/g, ' $1')}</span>
                                <span className="text-right font-semibold">{value instanceof Date ? format(value, 'PPP') : value.toString()}</span>
                            </div>
                        ))}
                    </div>
                )}
              </div>
              <DialogFooter>
                {step > 1 && (<Button type="button" variant="ghost" onClick={prevStep}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button>)}
                <div className='flex-grow' />
                {step < steps.length && (<Button type="button" onClick={nextStep}>Next<ArrowRight className="ml-2 h-4 w-4"/></Button>)}
                {step === steps.length && (<Button type="submit" disabled={isSubmitting}>{isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : null}Create Project</Button>)}
              </DialogFooter>
            </form>
          </Form>
      );
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" /> Create New Project
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl h-[80vh] flex flex-col">
        {renderContent()}
      </DialogContent>
    </Dialog>
  );
}
